In [1]:
import numpy as np


In [2]:
arr=np.array([1,2,3,4,5,6])
print(arr)

[1 2 3 4 5 6]


In [3]:
type(arr)

numpy.ndarray

In [5]:
arr2=np.array([[1,2,3],[4,5,6]])
print(arr2)
print(type(arr2))

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>


In [6]:
arr3=np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(arr3)
print(type(arr3))

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]
<class 'numpy.ndarray'>


In [7]:
arr3.ndim

3

In [8]:
arr3.shape

(1, 3, 3)

In [12]:
arr4=np.array([[[1,2,30],[4,5,7],[6,8,7]]])
print(arr4)


[[[ 1  2 30]
  [ 4  5  7]
  [ 6  8  7]]]


In [13]:
np.arange(1,9)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [14]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [16]:
np.linspace(1,10,6)

array([ 1. ,  2.8,  4.6,  6.4,  8.2, 10. ])

Differance between shallow copy and deep copy

shallowcopy:your array is change-shallocopyarray is change

deepcopy:your array is change but deepcopyarray is not change

In [17]:
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [18]:
shallowarr=arr2

In [19]:
shallowarr

array([[1, 2, 3],
       [4, 5, 6]])

In [20]:
deeparr=np.copy(arr2)

In [21]:
deeparr

array([[1, 2, 3],
       [4, 5, 6]])

In [22]:
arr2[0][0]=5
arr2

array([[5, 2, 3],
       [4, 5, 6]])

In [23]:
shallowarr

array([[5, 2, 3],
       [4, 5, 6]])

In [24]:
deeparr

array([[1, 2, 3],
       [4, 5, 6]])

fromfunction in numpy

In [25]:
np.fromfunction(lambda i,j:i*j,(4,4))

array([[0., 0., 0., 0.],
       [0., 1., 2., 3.],
       [0., 2., 4., 6.],
       [0., 3., 6., 9.]])

In [26]:
np.fromfunction(lambda i,j:i+j,(4,4))

array([[0., 1., 2., 3.],
       [1., 2., 3., 4.],
       [2., 3., 4., 5.],
       [3., 4., 5., 6.]])

In [27]:
np.fromfunction(lambda i,j:i==j,(4,4))

array([[ True, False, False, False],
       [False,  True, False, False],
       [False, False,  True, False],
       [False, False, False,  True]])

In [28]:
np.fromfunction(lambda i,j:i>j,(4,4))

array([[False, False, False, False],
       [ True, False, False, False],
       [ True,  True, False, False],
       [ True,  True,  True, False]])

to create an identity metrics

In [29]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [31]:
## Reashape function in numpy
dataset=np.linspace(2,9,50)

In [32]:
dataset

array([2.        , 2.14285714, 2.28571429, 2.42857143, 2.57142857,
       2.71428571, 2.85714286, 3.        , 3.14285714, 3.28571429,
       3.42857143, 3.57142857, 3.71428571, 3.85714286, 4.        ,
       4.14285714, 4.28571429, 4.42857143, 4.57142857, 4.71428571,
       4.85714286, 5.        , 5.14285714, 5.28571429, 5.42857143,
       5.57142857, 5.71428571, 5.85714286, 6.        , 6.14285714,
       6.28571429, 6.42857143, 6.57142857, 6.71428571, 6.85714286,
       7.        , 7.14285714, 7.28571429, 7.42857143, 7.57142857,
       7.71428571, 7.85714286, 8.        , 8.14285714, 8.28571429,
       8.42857143, 8.57142857, 8.71428571, 8.85714286, 9.        ])

In [33]:
dataset.shape

(50,)

In [42]:
dataset.reshape(2,1,25)

array([[[2.        , 2.14285714, 2.28571429, 2.42857143, 2.57142857,
         2.71428571, 2.85714286, 3.        , 3.14285714, 3.28571429,
         3.42857143, 3.57142857, 3.71428571, 3.85714286, 4.        ,
         4.14285714, 4.28571429, 4.42857143, 4.57142857, 4.71428571,
         4.85714286, 5.        , 5.14285714, 5.28571429, 5.42857143]],

       [[5.57142857, 5.71428571, 5.85714286, 6.        , 6.14285714,
         6.28571429, 6.42857143, 6.57142857, 6.71428571, 6.85714286,
         7.        , 7.14285714, 7.28571429, 7.42857143, 7.57142857,
         7.71428571, 7.85714286, 8.        , 8.14285714, 8.28571429,
         8.42857143, 8.57142857, 8.71428571, 8.85714286, 9.        ]]])